// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateSimilarity(arg1, arg2) {
  return window['go']['main']['App']['CalculateSimilarity'](arg1, arg2);
}

export function CleanString(arg1) {
  return window['go']['main']['App']['CleanString'](arg1);
}

export function ClearAICache() {
  return window['go']['main']['App']['ClearAICache']();
}

export function ExportResults(arg1) {
  return window['go']['main']['App']['ExportResults'](arg1);
}

export function GetAICacheInfo() {
  return window['go']['main']['App']['GetAICacheInfo']();
}

export function GetAIStatus() {
  return window['go']['main']['App']['GetAIStatus']();
}

export function OpenDailyReport() {
  return window['go']['main']['App']['OpenDailyReport']();
}

export function OpenFileA() {
  return window['go']['main']['App']['OpenFileA']();
}

export function OpenFileB() {
  return window['go']['main']['App']['OpenFileB']();
}

export function OpenMonthlyReport() {
  return window['go']['main']['App']['OpenMonthlyReport']();
}

export function ParseHeaders(arg1) {
  return window['go']['main']['App']['ParseHeaders'](arg1);
}

export function RunMatch(arg1) {
  return window['go']['main']['App']['RunMatch'](arg1);
}

export function RunMatchWithAI(arg1) {
  return window['go']['main']['App']['RunMatchWithAI'](arg1);
}

export function SetAIConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetAIConfig'](arg1, arg2, arg3);
}

export function SetAPIKey(arg1) {
  return window['go']['main']['App']['SetAPIKey'](arg1);
}
