// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CalculateSimilarity(arg1:string,arg2:string):Promise<number>;

export function CleanString(arg1:string):Promise<string>;

export function ClearAICache():Promise<string>;

export function ExportResults(arg1:Array<main.MatchResult>):Promise<string>;

export function GetAICacheInfo():Promise<main.AICacheInfo>;

export function GetAIStatus():Promise<Record<string, string>>;

export function OpenDailyReport():Promise<string>;

export function OpenFileA():Promise<string>;

export function OpenFileB():Promise<string>;

export function OpenMonthlyReport():Promise<string>;

export function ParseHeaders(arg1:string):Promise<Array<string>>;

export function RunMatch(arg1:main.MatchConfig):Promise<Array<main.MatchResult>>;

export function RunMatchWithAI(arg1:main.MatchConfig):Promise<Array<main.MatchResult>>;

export function SetAIConfig(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SetAPIKey(arg1:string):Promise<string>;
